name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  key: ${{github.event.head_commit.message}}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Test1
      run: echo contains(toJson(github.event.head_commit.message), 'one') || contains(toJson(github.event.head_commit.message), 'two') || contains(toJson(github.event.head_commit.message), 'three')
    - name: Test2
      run: echo $key
    - name: Test3
      if: contains(toJson(github.event.head_commit.message), 'one') || contains(toJson(github.event.head_commit.message), 'two') || contains(toJson(github.event.head_commit.message), 'three')
      run: echo $key
