name: Go

on:
  push:
    branches: [ JiaYongfei-patch-8 ]
  pull_request:
    branches: [ JiaYongfei-patch-8 ]

env:
  key: ${{github.event.head_commit.message}},${{github.event.pull_request.title}},${{github.event.pull_request.body}}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: echo $key
    - name: Test4
      if: contains(env.key, 'one') || contains(env.key, 'two')
      run: echo 'success'
