name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  key: ${{github.event.head_commit.message}}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Test
      run: echo $key
