name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  key: ${{github.event.head_commit.message}}
  key2: ${{github.event.pull_request.title}}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Test2
      run: echo $key
    - name: Test3
      run: echo $key2
    - name: Test4
      if: contains(toJson(github.event.head_commit.message), 'one') || contains(toJson(github.event.head_commit.message), 'two') || contains(toJson(github.event.pull_request.title), 'two')
      run: echo $key
