name: manual

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit'
        required: false
        default: ''
  repository_dispatch:
    types: [release]
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.commit }}
    - name: Set env
      run: if github.event_name = "push"; then echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV; else echo "VERSION=${github.sha}" >> $GITHUB_ENV; fi
    - name: Build
      run: |
        echo "Hello event name: ${{github.event_name}}"
        echo "Hello input: ${{ github.event.inputs.commit }}!"
        echo "Hello env version: ${{ env.VERSION }}!"
  #      ./test.sh
  #      go test -v ./test
  #      echo "Done"
  
  release1:
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name: Test
      run: echo ${{ env.VERSION }}
