name: manual

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit'
        required: false
        default: ${{ github.sha }}
  repository_dispatch:
    types: [release]
env:
  VERSION: ${{ github.event.inputs.commit }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.commit }}
    - name: Build
      run: |
        echo "Hello ${{ github.event.inputs.commit }}!"
        env
        ./test.sh
        go test -v ./test
        echo "Done"
