name: manual

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit'
        required: false
        default: ''
  repository_dispatch:
    types: [release]
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
env:
  VERSION: ${{ github.sha }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.commit }}
    - name: Set env
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Build
      run: |
        echo "Hello event path: ${{github.event_path}}"
        echo "Hello input: ${{ github.event.inputs.commit }}!"
        echo "Hello env version: ${{ env.VERSION }}!"
        env
        ./test.sh
        go test -v ./test
        echo "Done"
