name: manual

on:
  workflow_dispatch:
  repository_dispatch:
    types: [release]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: go test test
