name: manual

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit or Tag'
        required: false
        default: ''
  repository_dispatch:
    types: [release]
  push: 
    tags:
      - 'v*.*.*'

env:
  VERSION: ${{ github.event.inputs.commit }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - if: ${{github.event_name == 'push'}}
      name: Set tag as version
      run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - if: ${{ github.event.inputs.commit == '' }}
      name: Set defult version
      run: echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV
    - uses: actions/checkout@v2
      with:
        ref: ${{ env.VERSION }}
    - name: Build
      run: |
        echo "Hello event name: ${{github.event_name}}!"
        echo "Hello event name: ${{github.event.action}}!"
        echo "Hello input: ${{ github.event.inputs.commit }}!"
        echo "Hello env version: ${{ env.VERSION }}!"
        echo "Hello github sha: ${{ github.sha }}!"
        go test -v ./test
  #      ./test.sh
      
  #      echo "Done"
  
  release1:
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name: Test
      run: echo ${{ env.VERSION }}
